### ISSUE TITLE
Cannot build with xfce 4.16

### ISSUE THREAD

**Issue by schnitzeltony** [brianhsu/xfce4-hotcorner-plugin#11]
With 4.16 xfce removed gtk2 support and configure fails with

> -- Checking for modules 'libxfce4panel-1.0;libxfce4ui-1;libwnck-3.0'
> --   No package 'libxfce4panel-1.0' found
> --   No package 'libxfce4ui-1' found
> 

As a packager I ask: Do you intend to fix / continue this plugin?

**Comment by brianhsu** [comment]
@schnitzeltony Since I didn't use xfce anymore, this project has been abandoned and will not continue. Thanks.
